blank_issues_enabled: true
contact_links:
  - name: TraceTronic Support Center
    url: https://support.tracetronic.com
    about: Please report security vulnerabilities and non-public issues (i.e. NDA relevant information) here.
