name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: 'yes'