name: Check Markdown links

on:
  push:

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.16
